export const accountDescriptions: Record<string, string> = {
    // 1.1 Pessoal
    "1.1.1.1": "Salários. Proporcionalize para Finalística apenas funcionários das áreas fim. Ex: Fiscalização e Registro.",
    "1.1.1.2": "Gratificações. Lance em Finalística apenas se função exclusiva da atividade fim. Ex: Chefe de Fiscalização.",
    "1.1.1.3": "Anuênios. Proporcionalize para Finalística apenas funcionários das áreas fim. Ex: Fiscalização.",
    "1.1.1.4": "Férias. Proporcionalize para Finalística apenas funcionários das áreas fim. Ex: Registro.",
    "1.1.1.5": "13º Salário. Proporcionalize para Finalística apenas funcionários das áreas fim. Ex: Fiscalização.",
    "1.1.1.6": "Abono Férias. Lance em Finalística se funcionário da atividade fim. Ex: Fiscal.",
    "1.1.1.7": "1/3 Férias. Lance em Finalística se funcionário da atividade fim. Ex: Analista de Registro.",
    "1.1.1.8": "Horas Extras. Lance em Finalística se realizadas para atividade fim. Ex: Fiscalização noturna.",
    "1.1.1.9": "Estagiários. Lance em Finalística se atua em setor fim. Ex: Estagiário de Registro.",
    "1.1.1.10": "Adicional Noturno. Lance em Finalística se turno na atividade fim. Ex: Fiscalização.",
    "1.1.1.11": "Periculosidade. Lance em Finalística se risco na atividade fim. Ex: Fiscal de campo.",
    "1.1.1.12": "Vantagens. Lance em Finalística se funcionário da área fim. Ex: Registro.",
    "1.1.1.13": "Indenizações. Lance em Finalística se funcionário da área fim. Ex: Demissão de fiscal.",
    "1.1.1.14": "Insalubridade. Lance em Finalística se local insalubre na atividade fim. Ex: Arquivo de Processos.",
    "1.1.1.15": "Outras Remunerações. Lance em Finalística se funcionário da área fim.",

    // 1.1.2 Encargos
    "1.1.2.1": "INSS Patronal. Proporcional à folha da atividade fim. Ex: INSS dos Fiscais.",
    "1.1.2.2": "FGTS. Proporcional à folha da atividade fim. Ex: FGTS do setor de Registro.",
    "1.1.2.3": "PIS/PASEP. Proporcional à folha da atividade fim. Ex: Folha da Ética.",

    // 1.1.3 Benefícios
    "1.1.3.1": "Vale Transporte. Lance em Finalística os vales dos funcionários da área fim. Ex: Fiscais.",
    "1.1.3.2": "Vale Refeição. Lance em Finalística os vales dos funcionários da área fim. Ex: Registro.",
    "1.1.3.3": "Plano de Saúde. Lance em Finalística as vidas dos funcionários da área fim. Ex: Fiscalização.",
    "1.1.3.4": "Auxílio Odonto. Lance em Finalística os funcionários da área fim.",
    "1.1.3.5": "Auxílio Creche. Lance em Finalística os funcionários da área fim.",
    "1.1.3.6": "Auxílio Educação. Lance em Finalística se beneficiário é da área fim.",
    "1.1.3.7": "Lanche. Lance em Finalística se para setor fim ou evento fim. Ex: Reunião de Fiscalização.",
    "1.1.3.8": "Material Escolar. Lance em Finalística se funcionário da área fim.",
    "1.1.3.9": "Auxílio Funeral. Lance em Finalística se funcionário era da área fim.",
    "1.1.3.10": "Auxílio Babá. Lance em Finalística se funcionário da área fim.",
    "1.1.3.11": "Filho Excepcional. Lance em Finalística se funcionário da área fim.",
    "1.1.3.12": "Trabalho Híbrido. Lance em Finalística se funcionário da área fim.",
    "1.1.3.13": "Outros Benefícios. Lance em Finalística se funcionário da área fim.",

    // 1.2 Material Consumo
    "1.2.1.1": "Expediente. Lance em Finalística material exclusivo das áreas fim. Ex: Papel para autos de infração.",
    "1.2.1.2": "Impressos. Lance em Finalística formulários da área fim. Ex: Carteiras profissionais.",
    "1.2.1.3": "Carteiras. 100% Finalística (Registro). Ex: Cédulas de identidade.",
    "1.2.1.4": "Divulgação. Lance em Finalística material de campanhas institucionais da profissão. Ex: Folder Profissão.",
    "1.2.1.5": "Copa e Cozinha. Rateio ou uso exclusivo em eventos fim. Ex: Café para Plenária.",
    "1.2.1.6": "Alimentos. Rateio ou uso exclusivo. Ex: Lanche de Conselheiros em julgamento.",
    "1.2.1.7": "Limpeza. Rateio por área ocupada pelos setores fim. Ex: Limpeza sala Fiscalização.",
    "1.2.1.8": "Prêmios. Lance em Finalística se premiação profissional. Ex: Mérito Administrador.",
    "1.2.1.9": "Bandeiras/Placas. Lance em Finalística se homenagem profissional. Ex: Solenidade.",
    "1.2.1.10": "Informática. Lance em Finalística consumíveis de impressoras da área fim. Ex: Toner Fiscalização.",
    "1.2.1.11": "Elétrico. Lance em Finalística se manutenção da sala da área fim. Ex: Lâmpadas Registro.",
    "1.2.1.12": "Manut. Móveis. Lance em Finalística se móvel da área fim. Ex: Cadeira do Fiscal.",
    "1.2.1.13": "Manut. Imóveis. Rateio por área ocupada. Ex: Pintura sala Ética.",
    "1.2.1.14": "Gás. Geralmente Apoio, salvo uso específico.",
    "1.2.1.15": "Proteção. Lance em Finalística EPIs de fiscais. Ex: Coletes.",
    "1.2.1.16": "Sinalização. Lance em Finalística se placa orientativa ao profissional. Ex: 'Registro aqui'.",
    "1.2.1.17": "Combustível. Lance em Finalística gastos em diligências. Ex: Viatura Fiscalização.",
    "1.2.1.18": "Peças Auto. Lance em Finalística se veículo da área fim. Ex: Carro da Fiscalização.",
    "1.2.1.19": "Outros Materiais. Lance em Finalística se uso exclusivo área fim.",

    // 1.3 Terceiros PF
    "1.3.1.1": "INSS Autônomos. Proporcional ao serviço prestado à área fim.",
    "1.3.1.2": "Serviços PF. Lance em Finalística se serviço técnico para área fim. Ex: Parecerista ad hoc.",
    "1.3.1.3": "Verba Conselheiro. Lance em Finalística se atividade fim. Ex: Reunião de Câmara.",
    "1.3.1.4": "Verba Colaborador. Lance em Finalística se atividade fim. Ex: Palestrante técnico.",
    "1.3.1.5": "Outros PF. Lance em Finalística se serviço para área fim.",

    // 1.4 Diárias
    "1.4.1.1": "Diárias Conselheiros. Lance em Finalística se viagem para fim institucional. Ex: Julgamento.",
    "1.4.1.2": "Diárias Colaboradores. Lance em Finalística se missão técnica. Ex: Fiscal ad hoc.",
    "1.4.1.3": "Diárias Empregados. Lance em Finalística se viagem de fiscal/técnico. Ex: Fiscalização.",
    "1.4.1.4": "Inden. Conselheiro. Lance em Finalística se deslocamento para reunião fim. Ex: Plenária.",
    "1.4.1.5": "Inden. Colaborador. Lance em Finalística se deslocamento para evento fim.",

    // 1.5 Jetons
    "1.5.1.1": "Jetons à Conselheiros. 100% Finalística (Preenchimento automático - não editável).",

    // 1.6 Passagens
    "1.6.1.1": "Passagens País. Lance em Finalística se viagem para atividade fim. Ex: Fiscalização.",
    "1.6.1.2": "Passagens Exterior. Lance em Finalística se missão oficial da profissão. Ex: Congresso internacional.",

    // 1.7 Terceiros PJ
    "1.7.1.1": "Assessoria Admin. Geralmente Apoio.",
    "1.7.1.2": "Imprensa. Rateio ou Finalística se campanha profissional. Ex: Divulgação da profissão.",
    "1.7.1.3": "Inadimplentes. Lance 100% Finalística (Cobrança/Fiscalização). Ex: Serasa.",
    "1.7.1.4": "Assessoria Info. Lance em Finalística se suporte a sistemas fim. Ex: Sistema de Registro.",
    "1.7.1.5": "Serviços Info. Lance em Finalística se sistemas da área fim. Ex: Banco de dados profissionais.",
    "1.7.1.6": "Copa PJ. Rateio ou uso em eventos fim.",
    "1.7.1.7": "Gráficos. Lance em Finalística impressões técnicas. Ex: Livro de Legislação.",
    "1.7.1.8": "Medicina Trabalho. Proporcional aos funcionários da área fim.",
    "1.7.1.9": "Seleção/Treinamento. Lance em Finalística curso para fiscais/técnicos. Ex: Curso Fiscalização.",
    "1.7.1.10": "Emissão CIP. 100% Finalística (Registro). Ex: Confecção carteiras.",
    "1.7.1.11": "Cobrança Dívida. 100% Finalística (Recuperação de crédito). Ex: Empresa de cobrança.",
    "1.7.1.12": "Estágios. Lance em Finalística taxa de estagiários da área fim.",
    "1.7.1.13": "Publicidade. Lance em Finalística campanhas de valorização. Ex: Dia do Administrador.",
    "1.7.1.14": "Técnicos Espec. Lance em Finalística consultoria fim. Ex: Parecer jurídico ético.",
    "1.7.1.15": "Seguros. Rateio (Predial) ou Finalística (Vida Fiscais/Autos Fiscalização).",
    "1.7.1.16": "Mão de Obra. Geralmente Apoio (Limpeza/Portaria). Finalística se apoio administrativo direto.",
    "1.7.1.17": "Contábil. Geralmente Apoio.",
    "1.7.1.18": "Jurídica. Rateio ou Finalística se atuar em processos éticos/execução fiscal. Ex: 50% Fim.",
    "1.7.1.19": "Tradução. Lance em Finalística se documento técnico da profissão.",
    "1.7.1.20": "Foto/Vídeo. Lance em Finalística cobrindo eventos fim. Ex: Posse Conselheiros.",
    "1.7.1.21": "Jornalística. Lance em Finalística produção de conteúdo profissional. Ex: Revista do CRA.",
    "1.7.1.22": "Fretes. Lance em Finalística envio de carteiras/processos. Ex: Correio Registro.",
    "1.7.1.23": "Congressos. Lance em Finalística organização de eventos profissionais. Ex: Workshop Gestão.",
    "1.7.1.24": "Cópias. Rateio ou controle por centro de custo. Ex: Cópias Processos Éticos.",
    "1.7.1.25": "Condomínio. Rateio por área ocupada pelos setores fim.",
    "1.7.1.26": "Locação Imóveis. Rateio por área ocupada pelos setores fim. Ex: Sala Fiscalização.",
    "1.7.1.27": "Hospedagem PJ. Lance em Finalística se para palestrantes/fiscais em viagem.",
    "1.7.1.28": "Locação Bens Móveis. Lance em Finalística se equip. para área fim. Ex: Scanner Registro.",
    "1.7.1.29": "Locação Veículos. Lance em Finalística se para fiscalização. Ex: Carro Fiscal.",
    "1.7.1.30": "Manut. Bens Móveis. Lance em Finalística se equip. da área fim.",
    "1.7.1.31": "Manut. Veículos. Lance em Finalística se viatura da fiscalização.",
    "1.7.1.32": "Energia. Rateio por área ocupada. Ex: 60% Área Fim.",
    "1.7.1.33": "Água. Rateio por área ocupada ou per capita.",
    "1.7.1.34": "Correios. Lance em Finalística envio de documentos profissionais. Ex: Notificações.",
    "1.7.1.35": "Telecom. Rateio linhas fixas, Finalística celulares fiscais. Ex: Celular Fiscal.",
    "1.7.1.36": "SW/HW Manut. Rateio ou Finalística se equip. exclusivo da área fim.",
    "1.7.1.37": "Assinaturas. Lance em Finalística jornais/bases técnicas. Ex: LegisWeb.",
    "1.7.1.38": "Publicações. Lance em Finalística editais obrigatórios. Ex: Edital Eleição.",
    "1.7.1.39": "Revistas. Lance em Finalística assinaturas técnicas para consulta.",
    "1.7.1.40": "Certificação. Lance em Finalística tokens de fiscais/conselheiros.",
    "1.7.1.41": "Sites CFA. 100% Finalística (Integração sistêmica).",
    "1.7.1.42": "Manut. Sistemas. Lance em Finalística sistemas de registro/fiscalização.",
    "1.7.1.43": "Licenças SW. Lance em Finalística licenças específicas. Ex: SW Auditoria.",
    "1.7.1.44": "TI Soluções. Lance em Finalística se projeto para área fim.",
    "1.7.1.45": "Assessoria Parl. Lance em Finalística defesa da profissão no legislativo.",
    "1.7.1.46": "Apoio Reuniões. Lance em Finalística lanche/logística reuniões fim.",
    "1.7.1.47": "Auditoria/ISO. Geralmente Apoio (Institucional).",
    "1.7.1.48": "Jubileu. Apoio (Institucional) ou Finalística (Promoção).",
    "1.7.1.49": "Ativ. Culturais. Lance em Finalística se promove a profissão.",
    "1.7.1.50": "Tarifas Cartão. 100% Finalística (Recebimento de anuidades).",
    "1.7.1.51": "Banco Dados. 100% Finalística (Dados profissionais). Ex: Serpro.",
    "1.7.1.52": "Outros PJ. Lance em Finalística se serviço exclusivo área fim.",

    // 1.8 - 1.10 Outros
    "1.8.1.1": "Pedágios. Lance em Finalística se viagem de fiscalização.",
    "1.8.1.2": "Estacionamento. Lance em Finalística se viagem de fiscalização.",
    "1.8.1.3": "Táxi. Lance em Finalística se deslocamento para fiscalização/reunião fim.",
    "1.9.1.1": "Taxas. Lance em Finalística taxas judiciais de execução fiscal.",
    "1.9.1.2": "Tributos. Geralmente Apoio (IPTU rateio ou total).",
    "1.10.1.1": "Exerc. Anteriores. Segue a lógica da despesa original (Fim ou Apoio).",
    "1.10.1.2": "Pronto Pagto. Lance em Finalística se pequena despesa da área fim.",
    "1.10.1.3": "Custas Proc. 100% Finalística (Execução Fiscal).",
    "1.10.1.4": "Sentenças. Lance em Finalística se causa trabalhista de fiscal/etc.",
    "1.10.1.5": "Honorários. 100% Finalística (Cobrança).",
    "1.10.1.6": "Cartórios. Lance em Finalística protestos de CDA (Cobrança).",
    "1.10.1.7": "Indenizações. Lance em Finalística se dano causado por fiscalização.",
    "1.10.1.8": "Km Rodado. Lance em Finalística uso de veículo próprio para fiscalizar.",

    // 1.11 Financeiras
    "1.11.1.1": "Juros. Geralmente Apoio.",
    "1.11.1.2": "Atualização. Geralmente Apoio.",
    "1.11.2.1": "Taxas Bancárias. 100% Finalística (Boletos anuidade).",
    "1.11.2.2": "Cobrança. 100% Finalística (Tarifas cobrança).",
    "1.11.3.1": "Apoio Eventos. 100% Finalística (Fomento à profissão).",
    "1.11.3.2": "Proder Individual. 100% Finalística (Projeto Finalístico).",
    "1.11.3.3": "Proder Coletivo. 100% Finalística (Projeto Finalístico).",
    "1.11.3.4": "Crédito Capital. Transf. Capital.",
    "1.11.3.5": "Cota Parte. 100% Finalística (Preenchimento automático - não editável).",

    // 2 Capital
    "2.1.1.1": "Obras. Rateio ou Finalística se obra exclusiva setor fim (ex: Sala Fiscal).",
    "2.1.1.2": "Reformas. Rateio ou Finalística se reforma exclusiva setor fim.",
    "2.1.2.1": "Móveis. Lance em Finalística se para sala da área fim. Ex: Mesa do Fiscal.",
    "2.1.2.2": "Máquinas. Lance em Finalística se para uso da área fim.",
    "2.1.2.3": "Instalações. Rateio ou Finalística se exclusivo.",
    "2.1.2.4": "Veículos. Lance em Finalística se viatura fiscalização.",
    "2.1.2.5": "Copa/Cozinha. Geralmente Apoio.",
    "2.1.2.6": "Processamento Dados. Lance em Finalística computadores para área fim. Ex: PC Registro.",
    "2.1.2.7": "Biblioteca. 100% Finalística (Acervo técnico).",
    "2.1.2.8": "Obras Arte. Geralmente Apoio.",
    "2.3.1.1": "Imóveis. Sede (Apoio) ou Delegacia (Rateio).",
    "2.3.1.2": "Terrenos. Sede (Apoio).",
    "2.4.1.1": "Marcas. Institucional (Apoio).",
    "2.4.1.2": "Softwares. Lance em Finalística sistemas de fiscalização/registro.",
};
