export const ORGANIZATIONS = [
    { id: 'cfa', name: 'CFA - Conselho Federal', type: 'CFA' },
    { id: 'cra-ac', name: 'CRA-AC', type: 'CRA' },
    { id: 'cra-al', name: 'CRA-AL', type: 'CRA' },
    { id: 'cra-am', name: 'CRA-AM', type: 'CRA' },
    { id: 'cra-ap', name: 'CRA-AP', type: 'CRA' },
    { id: 'cra-ba', name: 'CRA-BA', type: 'CRA' },
    { id: 'cra-ce', name: 'CRA-CE', type: 'CRA' },
    { id: 'cra-df', name: 'CRA-DF', type: 'CRA' },
    { id: 'cra-es', name: 'CRA-ES', type: 'CRA' },
    { id: 'cra-go', name: 'CRA-GO', type: 'CRA' },
    { id: 'cra-ma', name: 'CRA-MA', type: 'CRA' },
    { id: 'cra-mg', name: 'CRA-MG', type: 'CRA' },
    { id: 'cra-ms', name: 'CRA-MS', type: 'CRA' },
    { id: 'cra-mt', name: 'CRA-MT', type: 'CRA' },
    { id: 'cra-pa', name: 'CRA-PA', type: 'CRA' },
    { id: 'cra-pb', name: 'CRA-PB', type: 'CRA' },
    { id: 'cra-pe', name: 'CRA-PE', type: 'CRA' },
    { id: 'cra-pi', name: 'CRA-PI', type: 'CRA' },
    { id: 'cra-pr', name: 'CRA-PR', type: 'CRA' },
    { id: 'cra-rj', name: 'CRA-RJ', type: 'CRA' },
    { id: 'cra-rn', name: 'CRA-RN', type: 'CRA' },
    { id: 'cra-ro', name: 'CRA-RO', type: 'CRA' },
    { id: 'cra-rr', name: 'CRA-RR', type: 'CRA' },
    { id: 'cra-rs', name: 'CRA-RS', type: 'CRA' },
    { id: 'cra-sc', name: 'CRA-SC', type: 'CRA' },
    { id: 'cra-se', name: 'CRA-SE', type: 'CRA' },
    { id: 'cra-sp', name: 'CRA-SP', type: 'CRA' },
    { id: 'cra-to', name: 'CRA-TO', type: 'CRA' },
] as const;
